name: fit_system_screenshot_example
description: Demonstrates how to use the fit_system_screenshot plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fit_system_screenshot:
    path: ../
  cupertino_icons: 1.0.2
  dio: 4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true