name: fit_system_screenshot
description: 让Flutter应用适配安卓系统的长截图
version: 1.0.4
homepage: https://github.com/YangLang116/fit_system_screenshot

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.xtu.flutter.fit.fit_system_screenshot
        pluginClass: FitSystemScreenshotPlugin